name = "NeurDS"
uuid = "2715ae87-f221-44ca-bd6b-586c1eb95788"
authors = ["James Scully"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
